export enum BusinessProcessBuilderStep {
    PROCESS_INFO = 'PROCESS_INFO',
    SELECT_SOURCES = 'SELECT_SOURCES',
    SELECT_DESTINATIONS = 'SELECT_DESTINATIONS',
    METADATA_GENERATION = 'METADATA_GENERATION',
} 